$schema: "http://json-schema.org/draft-07/schema#"
type: object
properties:
    main:
        type: array
        minItems: 1
        items:
            type: object
            anyOf:
              - properties:
                    include:
                        type: string
                        pattern: "^.+\\.ya?ml$"
                required: ["include"]
                additionalProperties: false
              - properties:
                    =#:
                        type: string
                required: ["=#"]
                additionalProperties: false
              - properties:
                    sql:
                        type: string
                required: ["sql"]
                additionalProperties: false
              - properties:
                    yaml:
                        type: string
                        pattern: "^.+\\s*=#\\s*.+$"
                required: ["yaml"]
                additionalProperties: false
              - properties:
                    json:
                        type: string
                        pattern: "^.+\\s*=#\\s*.+$"
                required: ["json"]
                additionalProperties: false
              - properties:
                    csv:
                        type: string
                        pattern: "^.+\\s*=#\\s*.+$"
                required: ["csv"]
                additionalProperties: false
required: ["main"]
additionalProperties: false
